name: Terraform CI

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.hcl"
      - ".pre-commit-config.yaml"
      - ".trivyignore"
      - ".trivyignore.yaml"
      - ".github/workflows/terraform-ci.yml"

  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*.hcl"
      - ".github/workflows/terraform-ci.yml"

  workflow_dispatch:

env:
  TF_IN_AUTOMATION: "true"

jobs:
  static:
    name: Static checks
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.15.8

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init -backend=false -input=false

      - name: Validate Terraform
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.2.2
        with:
          tflint_version: v0.64.0
          cache: true

      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint --recursive

      - name: Scan Terraform security
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          format: table
          hide-progress: true
          severity: HIGH,CRITICAL
          exit-code: "1"
          skip-dirs: "**/.terraform"
          tf-vars: envs/dev/terraform.tfvars

  plan:
    name: Terraform plan
    needs: static
    runs-on: ubuntu-latest

    if: >
      (github.event_name == 'push' &&
       github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' &&
       github.ref == 'refs/heads/main')

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.15.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_PLAN_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          allowed-account-ids: ${{ vars.AWS_ACCOUNT_ID }}
          role-session-name: terraform-plan-${{ github.run_id }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Initialize Terraform
        run: |
          terraform init \
            -input=false \
            -backend-config=envs/dev/backend.hcl

      - name: Terraform plan
        run: |
          terraform plan \
            -input=false \
            -no-color \
            -var-file=envs/dev/terraform.tfvars
